# Generated by Django 4.1.3 on 2022-11-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
