# Generated by Django 4.1.3 on 2022-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_aggregator', '0002_alter_link_downvotes_alter_link_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
